### ISSUE TITLE
resourceOwnerId参数的设置问题

### ISSUE THREAD

**Issue by taroyutao** [AliwareMQ/amqp-demos#1]
<rabbit:connection-factory id="connectionFactory" host="endpoint" port="5672"
                               username="#{userUtils.getUserName('ak',resourceOwnerId)}" password="#{userUtils.getPassord('sk')}"  virtual-host="test" requested-heartbeat="60" />

这个应该是账户的UID对吧，后面应该还要指定类型为Long吧，我测试的时候直接写UID报错，指定类型为Long就可以了。
  
    <rabbit:connection-factory id="connectionFactory" host="184821**16611234.mq-amqp.cn-hangzhou-a.aliyuncs.com" port="5672"
                               username="#{userUtils.getUserName('****',184821**16611234L)}" password="#{userUtils.getPassord('****')}"  virtual-host="yutaoamqptest" requested-heartbeat="60" />

**Comment by dxh031** [comment]
确实是long型的

**Comment by dxh031** [comment]
确实是long型的

**Comment by taroyutao** [comment]
Thanks。
